import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Download, FileText, Calendar, ClipboardCheck } from "lucide-react";
import type { DocumentWithResults } from "@shared/schema";
import { format } from "date-fns";

interface SummaryReportCardProps {
  document: DocumentWithResults;
}

export function SummaryReportCard({ document }: SummaryReportCardProps) {
  const handleDownloadReport = () => {
    if (!document.results) return;

    // Generate report content
    const reportContent = generateReportContent(document);

    // Create blob and download
    const blob = new Blob([reportContent], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const link = window.document.createElement('a');
    link.href = url;
    link.download = `medical-report-${document.id}-${format(new Date(), 'yyyy-MM-dd')}.txt`;
    window.document.body.appendChild(link);
    link.click();
    window.document.body.removeChild(link);
    window.URL.revokeObjectURL(url);
  };

  const generateReportContent = (doc: DocumentWithResults): string => {
    if (!doc.results) return '';

    const { classification, codes, summary } = doc.results;

    return `
╔══════════════════════════════════════════════════════════════════════════════╗
║                        MEDICAL DOCUMENT ANALYSIS REPORT                      ║
╚══════════════════════════════════════════════════════════════════════════════╝

DOCUMENT INFORMATION
────────────────────────────────────────────────────────────────────────────────
Document ID:          ${doc.id}
Filename:             ${doc.original_filename}
Upload Date:          ${format(new Date(doc.created_at), 'MMMM d, yyyy · h:mm a')}
Report Generated:     ${format(new Date(), 'MMMM d, yyyy · h:mm a')}

CLASSIFICATION RESULTS
────────────────────────────────────────────────────────────────────────────────
Document Type:        ${classification.document_type}
Confidence Score:     ${(classification.confidence * 100).toFixed(1)}%
Rationale:            ${classification.rationale}

Classification Evidence:
${classification.evidence && classification.evidence.length > 0
  ? classification.evidence.map((e, i) => `  ${i + 1}. ${e}`).join('\n')
  : '  No evidence provided'}

ICD-10 DIAGNOSTIC CODES
────────────────────────────────────────────────────────────────────────────────
${codes.codes.length === 0
  ? 'No diagnostic codes identified in this document.'
  : codes.codes.map((code, i) => `
Code ${i + 1}: ${code.code}
  Description:  ${code.description}
  Confidence:   ${(code.confidence * 100).toFixed(1)}%
  Evidence:
${code.evidence && code.evidence.length > 0
  ? code.evidence.map((e, j) => `    - ${e}`).join('\n')
  : '    - No evidence provided'}
`).join('\n')}

CLINICAL SUMMARY
────────────────────────────────────────────────────────────────────────────────
Confidence Score:     ${(summary.confidence * 100).toFixed(1)}%

Summary:
${summary.summary}

Summary Evidence:
${summary.evidence && summary.evidence.length > 0
  ? summary.evidence.map((e, i) => `  ${i + 1}. ${e}`).join('\n')
  : '  No evidence provided'}

═══════════════════════════════════════════════════════════════════════════════
End of Report
Generated by Medical Document AI Processing System
═══════════════════════════════════════════════════════════════════════════════
`.trim();
  };

  if (!document.results) {
    return null;
  }

  const { classification, codes, summary } = document.results;

  return (
    <Card className="border-primary/20">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <ClipboardCheck className="w-5 h-5 text-primary" />
            <CardTitle className="text-lg">Complete Analysis Report</CardTitle>
          </div>
          <Button
            onClick={handleDownloadReport}
            variant="default"
            size="sm"
            className="gap-2"
          >
            <Download className="w-4 h-4" />
            Download Report
          </Button>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-muted/50 p-4 rounded-lg space-y-3">
          <div className="flex items-start gap-2">
            <FileText className="w-4 h-4 text-muted-foreground mt-0.5" />
            <div className="flex-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide font-medium mb-1">
                Document
              </p>
              <p className="text-sm font-medium">{document.original_filename}</p>
            </div>
          </div>

          <div className="flex items-start gap-2">
            <Calendar className="w-4 h-4 text-muted-foreground mt-0.5" />
            <div className="flex-1">
              <p className="text-xs text-muted-foreground uppercase tracking-wide font-medium mb-1">
                Analyzed
              </p>
              <p className="text-sm font-medium">
                {format(new Date(document.created_at), 'MMMM d, yyyy · h:mm a')}
              </p>
            </div>
          </div>
        </div>

        <div className="space-y-2">
          <h4 className="text-sm font-semibold">Report Contents:</h4>
          <ul className="text-sm text-muted-foreground space-y-1.5">
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              Document classification: {classification.document_type}
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              {codes.codes.length} ICD-10 diagnostic code{codes.codes.length !== 1 ? 's' : ''}
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              Clinical summary with evidence
            </li>
            <li className="flex items-center gap-2">
              <span className="w-1.5 h-1.5 rounded-full bg-primary"></span>
              Confidence scores for all analyses
            </li>
          </ul>
        </div>

        <div className="pt-2 border-t">
          <p className="text-xs text-muted-foreground">
            The downloadable report contains all classification results, diagnostic codes,
            clinical summary, and supporting evidence in a formatted text document.
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
